// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCouVWZ9W7HT_5WOyK5G-yDw-2yB2lwX2M',
    appId: '1:179040760042:web:a62dfde8e9f7012bfc2793',
    messagingSenderId: '179040760042',
    projectId: 'instagramclone-84115',
    authDomain: 'instagramclone-84115.firebaseapp.com',
    storageBucket: 'instagramclone-84115.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-rslnpT4zN6dAL9kvA43TJ26TMdksuG0',
    appId: '1:179040760042:android:6c23af7141860e15fc2793',
    messagingSenderId: '179040760042',
    projectId: 'instagramclone-84115',
    storageBucket: 'instagramclone-84115.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWRYXhSLoapJ-IzR_HAuYvyB6KirBwr_g',
    appId: '1:179040760042:ios:ef0dbd0f70fc160ffc2793',
    messagingSenderId: '179040760042',
    projectId: 'instagramclone-84115',
    storageBucket: 'instagramclone-84115.appspot.com',
    iosBundleId: 'com.example.instagram',
  );
}
